import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import DemoOverlay from "@/components/DemoOverlay";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        data-theme="dark"
        className={`${poppins.variable} h-full antialiased`}
      >
        <body className="min-h-full bg-slate-950 text-slate-200 font-poppins flex flex-col">
          <DemoOverlay></DemoOverlay>
          <Navbar />
          <main className="flex-grow pt-20">{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
